server:
  port: 8761
spring:
  application:
    name: eirekaservice
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
