server:
  port: 8888
spring:
  application:
    name: localconfigservice
  cloud:
    config:
      server:
        native:
          search-locations: classpath:shared
      fail-fast: true
  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
