server:
  port: 8888
spring:
  application:
    name: remoteconfigservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaomaxiaomu/repositry-prod-.git
          search-paths: repositry-prod-
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
